name: "npm-cache"
description: "Cache npm modules and run npm ci if cache is not hit"
inputs:
  install_sfdx_scanner:
    description: "Install SFDX Scanner Plugin"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Cache node modules
      id: cache-nodemodules
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        # caching node_modules
        path: node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install Dependencies and copy config files and rules
      if: steps.cache-nodemodules.outputs.cache-hit != 'true'
      run: |
        npm ci --prefer-offline --no-audit
      shell: bash

    - name: Copy config files and rules only
      if: steps.cache-nodemodules.outputs.cache-hit == 'true'
      run: |
        npm run postinstall
      shell: bash

    - name: Install SF CLI and SFDX Scanner Plugin
      run: |
        npm install @salesforce/cli --location=global
        if [ "${{ inputs.install_sfdx_scanner }}" = "true" ]; then
          sf plugins install @salesforce/sfdx-scanner
        fi
      shell: bash
