name: Quality Checks

on:
  workflow_call:

jobs:
  lwc-jest:
    runs-on: ubuntu-latest
    name: "LWC Tests"
    steps:
      - uses: actions/checkout@v3
      - uses: Szandor72/devops-center-actions/.github/install-tooling@main
      - name: Run sfdx-lwc-jest
        run: |
          npm run test

  pmd-sobject:
    runs-on: ubuntu-latest
    name: "PMD for sObjects"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
      - uses: Szandor72/devops-center-actions/.github/install-tooling@main
      - name: "Show Rule Details"
        run: |
          cat ./.pmd/sobject-ruleset.xml
      - name: "Fetch all Files and prepare scan"
        run: |
          git fetch --all
          node .ci/prepare-scan.js
      - name: "Scan sObjects and Custom Fields"
        run: |
          sf scanner run --engine pmd --target "./force-app/**/*.field-meta.xml,./force-app/**/*.object-meta.xml" --pmdconfig ./.pmd/sobject-ruleset.xml --severity-threshold 3 --outfile "scan-results.json" --format json --normalize-severity

      - name: "Handle Scan Results"
        if: failure()
        run: |
          node .ci/parse-scan-results.js

  pmd-flow:
    runs-on: ubuntu-latest
    name: "PMD for Flows"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
      - uses: Szandor72/devops-center-actions/.github/install-tooling@main
      - name: "Show Rule Details"
        run: |
          cat ./.pmd/flow-ruleset.xml
      - name: "Fetch all Files and prepare scan"
        run: |
          git fetch --all
          node .ci/prepare-scan.js
      - name: "Scan Flows"
        run: |
          sf scanner run --engine pmd --target "./force-app/**/*.flow-meta.xml" --pmdconfig ./.pmd/flow-ruleset.xml --severity-threshold 3 --outfile "scan-results.json" --format json --normalize-severity
      - name: "Handle Scan Results"
        if: failure()
        run: |
          node .ci/parse-scan-results.js

  pmd-misc:
    runs-on: ubuntu-latest
    name: "PMD for other Metadata"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
      - uses: Szandor72/devops-center-actions/.github/install-tooling@main
      - name: "Show Rule Details"
        run: |
          cat ./.pmd/misc-ruleset.xml
      - name: "Fetch all Files and prepare scan"
        run: |
          git fetch --all
          node .ci/prepare-scan.js
      - name: "Scan Flows"
        run: |
          sf scanner run --engine pmd --target "./force-app/" --pmdconfig ./.pmd/misc-ruleset.xml --severity-threshold 3 --outfile "scan-results.json" --format json --normalize-severity
      - name: "Handle Scan Results"
        if: failure()
        run: |
          node .ci/parse-scan-results.js

  # commitlint is used to enforce commit message format
  # Since DevOps Center does its own commit msgs, this cannot be used
  # commitlint:
  #   runs-on: ubuntu-latest
  #   name: "Run Commitlint"
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     - uses: wagoid/commitlint-github-action@v5

  # stopped working, parsers cannot be inferred for xml and apex; no clue why as plugins seem to be installed but not
  # TODO hardcode plugin versions - local tests showed it will help
  prettier-formatting:
    name: "Format with Prettier"
    # needs: [lwc-jest, pmd-sobject, pmd-flow, pmd-misc]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: Szandor72/devops-center-actions/.github/install-tooling@main
      - uses: creyD/prettier_action@v4.3
        with:
          prettier_version: 2.6.0
          prettier_options: --write **/*.{cls,cmp,component,css,html,js,json,md,page,trigger,xml,yaml,yml} --no-error-on-unmatched-pattern
          same_commit: True
          only_changed: True
          prettier_plugins: "prettier-plugin-apex @prettier/plugin-xml"
