name: SF(DX) Scanner

on:
  workflow_call:

jobs:
  prepare-scan:
    runs-on: ubuntu-latest
    name: "Prepare and initiate scan"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Salesforce CLI and Run Commands
        uses: docker://salesforce/cli:latest-full
        with:
          args: |
            sf plugins install @salesforce/sfdx-scanner
            node .\scripts\ci\prepare-scan.js
            sf scanner run --target .\new-files-to-scan\ --engine pmd --category "Security, Performance"
            sf scanner run --target .\modified-files-to-scan\ --engine pmd --category "Security, Performance"
