name: Validate Deployment

on:
  workflow_call:

jobs:
  validate-deployment:
    runs-on: ubuntu-latest
    name: "Test Deployment and Test Runs"
    steps:
      - uses: actions/checkout@v4
      - uses: Szandor72/devops-center-actions/.github/install-tooling@main
        with:
          install_sfdx_scanner: false
      - name: "Populate auth file with INTEGRATION_SANDBOX_SFDX_URL secret"
        run: |
          echo ${{ secrets.INTEGRATION_SANDBOX_SFDX_URL}} > ./INTEGRATION_SANDBOX_SFDX_URL.auth

      - name: "Populate auth file with DEVOPS_CENTER_HOME_PROD secret"
        run: |
          echo ${{ secrets.PROD_DEVOPS_CENTER_HOME_SFDX_URL}} > ./PROD_DEVOPS_CENTER_HOME_SFDX_URL.auth

      - name: Authenticate against DevOps Center Home (Production Org)
        run:
          sf org login sfdx-url --sfdx-url-file ./PROD_DEVOPS_CENTER_HOME_SFDX_URL.auth
          --set-default --alias PROD_DEVOPS_CENTER_HOME

      - name: Create Manifest File for Deployment
        run: |
          node .ci/create-manifest.js ${{ github.event.pull_request.head.ref }}
          cat package.xml

      - name: Authenticate against integration sandbox
        run:
          sf org login sfdx-url --sfdx-url-file ./INTEGRATION_SANDBOX_SFDX_URL.auth
          --set-default --alias integration_sandbox

      - name: Validate deployment and run local tests
        run: sf project deploy validate --manifest package.xml --wait 120
          --test-level=RunLocalTests --target-org integration_sandbox
